version: '3.4'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb_data:/bitnami'
    ports:
      - 3306:3306
  redmine:
    image: 'bitnami/redmine:3.2.3-r1'
    restart: always
    ports:
      - '8081:3000'
    volumes:
      - 'redmine_data:/bitnami'
    environment:
      REDMINE_DB_MYSQL: mariadb
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
